### ISSUE TITLE
Log error warning: "Undefined constant "JW_THEME_PATH"

### ISSUE THREAD

**Issue by tms-honghoang** [juzaweb/cms#318]
How to fix errors: "Undefined constant "JW_THEME_PATH"

```
[2023-06-15 10:03:27] local.ERROR: Undefined constant "JW_THEME_PATH" {"exception":"[object] (Error(code: 0): Undefined constant \"JW_THEME_PATH\" at /Users/mac/Project/juza/modules/CMS/config/juzaweb.php:102)
[stacktrace]
#0 /Users/mac/Project/juza/vendor/laravel/framework/src/Illuminate/Support/ServiceProvider.php(138): require()
#1 /Users/mac/Project/juza/modules/CMS/Providers/CmsServiceProvider.php(141): Illuminate\\Support\\ServiceProvider->mergeConfigFrom('/Users/mac/Proj...', 'juzaweb')
#2 /Users/mac/Project/juza/modules/CMS/Providers/CmsServiceProvider.php(134): Juzaweb\\CMS\\Providers\\CmsServiceProvider->registerConfigs()
#3 /Users/mac/Project/juza/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(686): Juzaweb\\CMS\\Providers\\CmsServiceProvider->register()
#4 /Users/mac/Project/juza/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php(75): Illuminate\\Foundation\\Application->register(Object(Juzaweb\\CMS\\Providers\\CmsServiceProvider))
#5 /Users/mac/Project/juza/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(663): Illuminate\\Foundation\\ProviderRepository->load(Array)
#6 /Users/mac/Project/juza/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/RegisterProviders.php(17): Illuminate\\Foundation\\Application->registerConfiguredProviders()
#7 /Users/mac/Project/juza/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(239): Illuminate\\Foundation\\Bootstrap\\RegisterProviders->bootstrap(Object(Juzaweb\\CMS\\Support\\Application))
#8 /Users/mac/Project/juza/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(310): Illuminate\\Foundation\\Application->bootstrapWith(Array)
#9 /Users/mac/Project/juza/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(127): Illuminate\\Foundation\\Console\\Kernel->bootstrap()
#10 Command line code(1): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#11 {main}
"} 
```

**Comment by juzaweb** [comment]
- Please give me more information about your error, like version, specific case of error. 
- Try checking your file modules/define.php and make sure it has the line like below:
```
if (!defined('JW_THEME_PATH')) {
    define('JW_THEME_PATH', JW_BASE_PATH . '/themes');
}
```
- Try checking your file `public/index.php` and make sure it has the line like below:
```
require __DIR__.'/../modules/autoload.php';
```
